[tool.poetry]
name = "scripts"
package-mode = false
description = "DeepL OpenAPI specification and associated scripts"
license = "MIT"

[tool.poetry.scripts]
convert_to_json = "scripts.convert_to_json:main"

[tool.poetry.dependencies]
python = ">=3.7"
click = "^8.1.7"
ruamel-yaml = "^0.18.5"
